### ISSUE TITLE
EPIC: Complete SRS documentation

### ISSUE THREAD

**Issue by lucasichen** [lilweege/SyntaxSentinels#19]
- [x] #20
- [x] #21
- [x] #22
- [x] #23
- [x] #24
- [x] #25
- [x] #26
- [x] #27
- [x] #28
- [x] #29
- [x] #30
- [x] #31
- [x] #32
- [x] #33
- [x] #34
- [x] #35
- [x] #36
- [x] #37
- [x] #38
- [x] #39
- [x] #40
- [x] #41
- [x] #42
- [x] #43

**Comment by lilweege** [comment]
All that's left (hopefully) is minor fixups. I'm going to go over the document and fix spelling wherever necessary.
